/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG_DASH_DASH = 1,
  aux_sym_comment_token1 = 2,
  aux_sym_comment_token2 = 3,
  aux_sym_comment_token3 = 4,
  anon_sym_DASH_DASH_GT = 5,
  sym_line_continuation = 6,
  sym_text = 7,
  anon_sym_DOLLAR = 8,
  aux_sym_naked_variable_token1 = 9,
  anon_sym_DOT = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_number = 13,
  aux_sym_string_token1 = 14,
  aux_sym_string_token2 = 15,
  sym_source_file = 16,
  sym_item = 17,
  sym_comment = 18,
  sym_naked_variable = 19,
  sym_dotProperty = 20,
  sym_squareProperty = 21,
  sym_string = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_comment_repeat1 = 24,
  aux_sym_naked_variable_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [aux_sym_comment_token3] = "comment_token3",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_line_continuation] = "line_continuation",
  [sym_text] = "text",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_naked_variable_token1] = "naked_variable_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_source_file] = "source_file",
  [sym_item] = "item",
  [sym_comment] = "comment",
  [sym_naked_variable] = "naked_variable",
  [sym_dotProperty] = "dotProperty",
  [sym_squareProperty] = "squareProperty",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_naked_variable_repeat1] = "naked_variable_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [aux_sym_comment_token3] = aux_sym_comment_token3,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_line_continuation] = sym_line_continuation,
  [sym_text] = sym_text,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_naked_variable_token1] = aux_sym_naked_variable_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_source_file] = sym_source_file,
  [sym_item] = sym_item,
  [sym_comment] = sym_comment,
  [sym_naked_variable] = sym_naked_variable,
  [sym_dotProperty] = sym_dotProperty,
  [sym_squareProperty] = sym_squareProperty,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_naked_variable_repeat1] = aux_sym_naked_variable_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_line_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_naked_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_naked_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_dotProperty] = {
    .visible = true,
    .named = true,
  },
  [sym_squareProperty] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_naked_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 2,
  [10] = 3,
  [11] = 8,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 17,
  [22] = 16,
  [23] = 15,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 24,
  [31] = 26,
  [32] = 32,
  [33] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '\'') ADVANCE(12);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == '<') ADVANCE(4);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == ']') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\r') ADVANCE(1);
      if ((!eof && lookahead == 00) ||
          lookahead == '\n') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '\r') ADVANCE(19);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(19);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == ' ' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead == ' ' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(10);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(23);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(6);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '\r') ADVANCE(26);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(26);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\r') ADVANCE(27);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(27);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\r') ADVANCE(1);
      if ((!eof && lookahead == 00) ||
          lookahead == '\n') ADVANCE(24);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\r') ADVANCE(19);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(17);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '!') ADVANCE(9);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_comment_token3);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_line_continuation);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\r') ADVANCE(1);
      if ((!eof && lookahead == 00) ||
          lookahead == '\n') ADVANCE(24);
      if (lookahead == ' ' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\r') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(26);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= ']') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\r') ADVANCE(27);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(27);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= ']') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(9);
      if (lookahead == ' ' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_naked_variable_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {(TSStateId)(-1),},
  [33] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(1),
    [aux_sym_comment_token3] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [sym_line_continuation] = ACTIONS(5),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym_naked_variable_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym_item] = STATE(19),
    [sym_comment] = STATE(1),
    [sym_naked_variable] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(9),
    [sym_line_continuation] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [anon_sym_DOLLAR] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_DOT,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_naked_variable_repeat1,
    ACTIONS(19), 2,
      sym_text,
      anon_sym_DOLLAR,
    STATE(15), 2,
      sym_dotProperty,
      sym_squareProperty,
  [30] = 9,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(21), 1,
      anon_sym_DOT,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_naked_variable_repeat1,
    ACTIONS(27), 2,
      sym_text,
      anon_sym_DOLLAR,
    STATE(15), 2,
      sym_dotProperty,
      sym_squareProperty,
  [60] = 8,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_DOT,
    ACTIONS(36), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 2,
      sym_text,
      anon_sym_DOLLAR,
    STATE(4), 2,
      sym_comment,
      aux_sym_naked_variable_repeat1,
    STATE(15), 2,
      sym_dotProperty,
      sym_squareProperty,
  [88] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(42), 1,
      anon_sym_LBRACK,
    STATE(5), 2,
      sym_comment,
      aux_sym_naked_variable_repeat1,
    STATE(23), 2,
      sym_dotProperty,
      sym_squareProperty,
  [112] = 9,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_source_file_repeat1,
    STATE(19), 1,
      sym_item,
    STATE(20), 1,
      sym_naked_variable,
  [140] = 8,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym_text,
    ACTIONS(52), 1,
      anon_sym_DOLLAR,
    STATE(19), 1,
      sym_item,
    STATE(20), 1,
      sym_naked_variable,
    STATE(7), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [166] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(55), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      sym_number,
    STATE(8), 1,
      sym_comment,
    ACTIONS(59), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(26), 2,
      sym_naked_variable,
      sym_string,
  [190] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(61), 1,
      anon_sym_DOT,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_naked_variable_repeat1,
    STATE(23), 2,
      sym_dotProperty,
      sym_squareProperty,
  [216] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    ACTIONS(61), 1,
      anon_sym_DOT,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    STATE(5), 1,
      aux_sym_naked_variable_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(23), 2,
      sym_dotProperty,
      sym_squareProperty,
  [242] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(55), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      sym_number,
    STATE(11), 1,
      sym_comment,
    ACTIONS(59), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(31), 2,
      sym_naked_variable,
      sym_string,
  [266] = 6,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(69), 1,
      anon_sym_DASH_DASH_GT,
    STATE(12), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_comment_repeat1,
    ACTIONS(67), 3,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [287] = 6,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(71), 1,
      anon_sym_DASH_DASH_GT,
    STATE(12), 1,
      aux_sym_comment_repeat1,
    STATE(13), 1,
      sym_comment,
    ACTIONS(67), 3,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [308] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(76), 1,
      anon_sym_DASH_DASH_GT,
    STATE(14), 2,
      sym_comment,
      aux_sym_comment_repeat1,
    ACTIONS(73), 3,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [327] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym_comment,
    ACTIONS(80), 4,
      sym_text,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [346] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym_comment,
    ACTIONS(84), 4,
      sym_text,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [365] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_comment,
    ACTIONS(88), 4,
      sym_text,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [384] = 4,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    STATE(18), 1,
      sym_comment,
    ACTIONS(90), 4,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
      anon_sym_DASH_DASH_GT,
  [400] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_comment,
    ACTIONS(94), 2,
      sym_text,
      anon_sym_DOLLAR,
  [417] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_comment,
    ACTIONS(98), 2,
      sym_text,
      anon_sym_DOLLAR,
  [434] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(21), 1,
      sym_comment,
    ACTIONS(86), 3,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [449] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(22), 1,
      sym_comment,
    ACTIONS(82), 3,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [464] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(23), 1,
      sym_comment,
    ACTIONS(78), 3,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [479] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(100), 1,
      aux_sym_naked_variable_token1,
    STATE(24), 1,
      sym_comment,
  [492] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(102), 1,
      anon_sym_RBRACK,
    STATE(25), 1,
      sym_comment,
  [505] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(104), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      sym_comment,
  [518] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym_comment,
  [531] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(108), 1,
      aux_sym_naked_variable_token1,
    STATE(28), 1,
      sym_comment,
  [544] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(110), 1,
      aux_sym_naked_variable_token1,
    STATE(29), 1,
      sym_comment,
  [557] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(112), 1,
      aux_sym_naked_variable_token1,
    STATE(30), 1,
      sym_comment,
  [570] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(114), 1,
      anon_sym_RBRACK,
    STATE(31), 1,
      sym_comment,
  [583] = 1,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
  [587] = 1,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 88,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 166,
  [SMALL_STATE(9)] = 190,
  [SMALL_STATE(10)] = 216,
  [SMALL_STATE(11)] = 242,
  [SMALL_STATE(12)] = 266,
  [SMALL_STATE(13)] = 287,
  [SMALL_STATE(14)] = 308,
  [SMALL_STATE(15)] = 327,
  [SMALL_STATE(16)] = 346,
  [SMALL_STATE(17)] = 365,
  [SMALL_STATE(18)] = 384,
  [SMALL_STATE(19)] = 400,
  [SMALL_STATE(20)] = 417,
  [SMALL_STATE(21)] = 434,
  [SMALL_STATE(22)] = 449,
  [SMALL_STATE(23)] = 464,
  [SMALL_STATE(24)] = 479,
  [SMALL_STATE(25)] = 492,
  [SMALL_STATE(26)] = 505,
  [SMALL_STATE(27)] = 518,
  [SMALL_STATE(28)] = 531,
  [SMALL_STATE(29)] = 544,
  [SMALL_STATE(30)] = 557,
  [SMALL_STATE(31)] = 570,
  [SMALL_STATE(32)] = 583,
  [SMALL_STATE(33)] = 587,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_naked_variable, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_naked_variable, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_naked_variable, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_naked_variable, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_naked_variable_repeat1, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotProperty, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotProperty, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_squareProperty, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_squareProperty, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sugarcube(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sugarcube",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
