/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 81
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG_DASH_DASH = 1,
  aux_sym_comment_token1 = 2,
  aux_sym_comment_token2 = 3,
  aux_sym_comment_token3 = 4,
  anon_sym_DASH_DASH_GT = 5,
  sym_line_continuation = 6,
  sym_word = 7,
  sym_word_link = 8,
  anon_sym_DOLLAR = 9,
  aux_sym_naked_variable_token1 = 10,
  anon_sym_DOT = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  sym_number = 14,
  aux_sym_string_token1 = 15,
  aux_sym_string_token2 = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 21,
  anon_sym_LBRACE_LBRACE_LBRACE = 22,
  anon_sym_RBRACE_RBRACE_RBRACE = 23,
  anon_sym_LTnowiki_GT = 24,
  anon_sym_LT_SLASHnowiki_GT = 25,
  anon_sym_LBRACK_LBRACK = 26,
  anon_sym_PIPE = 27,
  anon_sym_RBRACK_LBRACK = 28,
  anon_sym_RBRACK_RBRACK = 29,
  sym_source_file = 30,
  sym_item = 31,
  sym_comment = 32,
  sym_naked_variable = 33,
  sym_dotProperty = 34,
  sym_squareProperty = 35,
  sym_string = 36,
  sym_expression = 37,
  sym_triple_quotes_naked_variable = 38,
  sym_code_naked_variable = 39,
  sym_nowiki_naked_variable = 40,
  sym_escaped_naked_variable = 41,
  sym_link = 42,
  sym_literal = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_comment_repeat1 = 45,
  aux_sym_naked_variable_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [aux_sym_comment_token3] = "comment_token3",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_line_continuation] = "line_continuation",
  [sym_word] = "word",
  [sym_word_link] = "word_link",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_naked_variable_token1] = "naked_variable_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [anon_sym_LBRACE_LBRACE_LBRACE] = "{{{",
  [anon_sym_RBRACE_RBRACE_RBRACE] = "}}}",
  [anon_sym_LTnowiki_GT] = "<nowiki>",
  [anon_sym_LT_SLASHnowiki_GT] = "</nowiki>",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACK_LBRACK] = "][",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_source_file] = "source_file",
  [sym_item] = "item",
  [sym_comment] = "comment",
  [sym_naked_variable] = "naked_variable",
  [sym_dotProperty] = "dotProperty",
  [sym_squareProperty] = "squareProperty",
  [sym_string] = "string",
  [sym_expression] = "expression",
  [sym_triple_quotes_naked_variable] = "triple_quotes_naked_variable",
  [sym_code_naked_variable] = "code_naked_variable",
  [sym_nowiki_naked_variable] = "nowiki_naked_variable",
  [sym_escaped_naked_variable] = "escaped_naked_variable",
  [sym_link] = "link",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_naked_variable_repeat1] = "naked_variable_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [aux_sym_comment_token3] = aux_sym_comment_token3,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_line_continuation] = sym_line_continuation,
  [sym_word] = sym_word,
  [sym_word_link] = sym_word_link,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_naked_variable_token1] = aux_sym_naked_variable_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [anon_sym_LBRACE_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE_RBRACE,
  [anon_sym_LTnowiki_GT] = anon_sym_LTnowiki_GT,
  [anon_sym_LT_SLASHnowiki_GT] = anon_sym_LT_SLASHnowiki_GT,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACK_LBRACK] = anon_sym_RBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_item] = sym_item,
  [sym_comment] = sym_comment,
  [sym_naked_variable] = sym_naked_variable,
  [sym_dotProperty] = sym_dotProperty,
  [sym_squareProperty] = sym_squareProperty,
  [sym_string] = sym_string,
  [sym_expression] = sym_expression,
  [sym_triple_quotes_naked_variable] = sym_triple_quotes_naked_variable,
  [sym_code_naked_variable] = sym_code_naked_variable,
  [sym_nowiki_naked_variable] = sym_nowiki_naked_variable,
  [sym_escaped_naked_variable] = sym_escaped_naked_variable,
  [sym_link] = sym_link,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_naked_variable_repeat1] = aux_sym_naked_variable_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_line_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_word_link] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_naked_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTnowiki_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHnowiki_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_naked_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_dotProperty] = {
    .visible = true,
    .named = true,
  },
  [sym_squareProperty] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_triple_quotes_naked_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_code_naked_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_nowiki_naked_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_naked_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_naked_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 6,
  [11] = 5,
  [12] = 4,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 6,
  [21] = 5,
  [22] = 4,
  [23] = 7,
  [24] = 8,
  [25] = 9,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 8,
  [33] = 33,
  [34] = 7,
  [35] = 35,
  [36] = 9,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 39,
  [42] = 40,
  [43] = 38,
  [44] = 38,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 16,
  [50] = 15,
  [51] = 17,
  [52] = 13,
  [53] = 14,
  [54] = 45,
  [55] = 45,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 65,
  [74] = 64,
  [75] = 75,
  [76] = 65,
  [77] = 64,
  [78] = 78,
  [79] = 79,
  [80] = 80,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(13);
      if (lookahead == '*') ADVANCE(93);
      if (lookahead == '+') ADVANCE(90);
      if (lookahead == '-') ADVANCE(92);
      if (lookahead == '.') ADVANCE(82);
      if (lookahead == '/') ADVANCE(94);
      if (lookahead == '<') ADVANCE(8);
      if (lookahead == '[') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == ']') ADVANCE(85);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '|') ADVANCE(101);
      if (lookahead == '}') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == '\r') ADVANCE(1);
      if ((!eof && lookahead == 00) ||
          lookahead == '\n') ADVANCE(46);
      END_STATE();
    case 3:
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '*') ADVANCE(93);
      if (lookahead == '+') ADVANCE(90);
      if (lookahead == '-') ADVANCE(91);
      if (lookahead == '.') ADVANCE(82);
      if (lookahead == '/') ADVANCE(94);
      if (lookahead == '<') ADVANCE(7);
      if (lookahead == '[') ADVANCE(83);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == ']') ADVANCE(85);
      if (lookahead == '}') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\r') SKIP(4);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(13);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == ']') ADVANCE(20);
      if (lookahead == '|') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 5:
      if (lookahead == '\r') ADVANCE(41);
      if (lookahead == '-') ADVANCE(14);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(41);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '!') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(95);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '"') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == '\'') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(45);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 18:
      if (lookahead == '>') ADVANCE(98);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(99);
      END_STATE();
    case 20:
      if (lookahead == '[') ADVANCE(102);
      if (lookahead == ']') ADVANCE(103);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 25:
      if (lookahead == 'k') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 'k') ADVANCE(23);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 30:
      if (lookahead == 'w') ADVANCE(21);
      END_STATE();
    case 31:
      if (lookahead == 'w') ADVANCE(24);
      END_STATE();
    case 32:
      if (lookahead == '{') ADVANCE(96);
      END_STATE();
    case 33:
      if (lookahead == '{') ADVANCE(32);
      END_STATE();
    case 34:
      if (lookahead == '}') ADVANCE(97);
      END_STATE();
    case 35:
      if (lookahead == '}') ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\r') ADVANCE(1);
      if ((!eof && lookahead == 00) ||
          lookahead == '\n') ADVANCE(46);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\r') ADVANCE(41);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ' ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '!') ADVANCE(16);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token3);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_line_continuation);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_line_continuation);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_word);
      if ((!eof && lookahead == 00)) ADVANCE(46);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\r') SKIP(49);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '[') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\r') SKIP(50);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '*') ADVANCE(93);
      if (lookahead == '+') ADVANCE(90);
      if (lookahead == '-') ADVANCE(91);
      if (lookahead == '.') ADVANCE(82);
      if (lookahead == '/') ADVANCE(94);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '[') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\r') SKIP(51);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '.') ADVANCE(82);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '[') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\r') SKIP(52);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '*') ADVANCE(93);
      if (lookahead == '+') ADVANCE(90);
      if (lookahead == '-') ADVANCE(91);
      if (lookahead == '/') ADVANCE(94);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '[') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '!') ADVANCE(58);
      if (lookahead == 'n') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(68);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\'') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '"') ADVANCE(87);
      if (lookahead == '\'') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '"') ADVANCE(68);
      if (lookahead == '\'') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '>') ADVANCE(98);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '[') ADVANCE(100);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(63);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'i') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'k') ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'o') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'w') ADVANCE(61);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '{') ADVANCE(96);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '{') ADVANCE(66);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_word);
      if (eof) ADVANCE(36);
      if (lookahead == '\r') SKIP(69);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '[') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(69);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_word);
      if (eof) ADVANCE(36);
      if (lookahead == '\r') SKIP(70);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '*') ADVANCE(93);
      if (lookahead == '+') ADVANCE(90);
      if (lookahead == '-') ADVANCE(91);
      if (lookahead == '.') ADVANCE(82);
      if (lookahead == '/') ADVANCE(94);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '[') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_word);
      if (eof) ADVANCE(36);
      if (lookahead == '\r') SKIP(71);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '.') ADVANCE(82);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '[') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_word);
      if (eof) ADVANCE(36);
      if (lookahead == '\r') SKIP(72);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '*') ADVANCE(93);
      if (lookahead == '+') ADVANCE(90);
      if (lookahead == '-') ADVANCE(91);
      if (lookahead == '/') ADVANCE(94);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '[') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '{') ADVANCE(67);
      if (lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_word_link);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_word_link);
      if (lookahead == '\r') ADVANCE(74);
      if (lookahead == '<') ADVANCE(76);
      if (lookahead == '\\') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == 0x200b ||
          lookahead == 0x2060 ||
          lookahead == 0xfeff) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_word_link);
      if (lookahead == '\r') ADVANCE(73);
      if ((!eof && lookahead == 00) ||
          lookahead == '\n') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_word_link);
      if (lookahead == '!') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_word_link);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_word_link);
      if (lookahead == '-') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_word_link);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_naked_variable_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(100);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(95);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_LBRACE);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE_RBRACE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_LTnowiki_GT);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LT_SLASHnowiki_GT);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_RBRACK_LBRACK);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 69},
  [2] = {.lex_state = 69},
  [3] = {.lex_state = 69},
  [4] = {.lex_state = 70},
  [5] = {.lex_state = 70},
  [6] = {.lex_state = 70},
  [7] = {.lex_state = 70},
  [8] = {.lex_state = 70},
  [9] = {.lex_state = 70},
  [10] = {.lex_state = 71},
  [11] = {.lex_state = 71},
  [12] = {.lex_state = 71},
  [13] = {.lex_state = 72},
  [14] = {.lex_state = 72},
  [15] = {.lex_state = 72},
  [16] = {.lex_state = 72},
  [17] = {.lex_state = 72},
  [18] = {.lex_state = 72},
  [19] = {.lex_state = 72},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 71},
  [24] = {.lex_state = 71},
  [25] = {.lex_state = 71},
  [26] = {.lex_state = 69},
  [27] = {.lex_state = 69},
  [28] = {.lex_state = 69},
  [29] = {.lex_state = 69},
  [30] = {.lex_state = 69},
  [31] = {.lex_state = 69},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 69},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 69},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 69},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 74},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 74},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 74},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 74},
  [79] = {(TSStateId)(-1),},
  [80] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(3),
    [aux_sym_comment_token3] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [sym_line_continuation] = ACTIONS(5),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym_naked_variable_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LTnowiki_GT] = ACTIONS(1),
    [anon_sym_LT_SLASHnowiki_GT] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(72),
    [sym_item] = STATE(29),
    [sym_comment] = STATE(1),
    [sym_naked_variable] = STATE(18),
    [sym_string] = STATE(15),
    [sym_expression] = STATE(19),
    [sym_triple_quotes_naked_variable] = STATE(27),
    [sym_code_naked_variable] = STATE(27),
    [sym_nowiki_naked_variable] = STATE(27),
    [sym_escaped_naked_variable] = STATE(27),
    [sym_link] = STATE(27),
    [sym_literal] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(9),
    [sym_line_continuation] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [anon_sym_DOLLAR] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [aux_sym_string_token1] = ACTIONS(19),
    [aux_sym_string_token2] = ACTIONS(19),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(21),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(23),
    [anon_sym_LTnowiki_GT] = ACTIONS(25),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(27),
  },
  [STATE(2)] = {
    [sym_item] = STATE(29),
    [sym_comment] = STATE(2),
    [sym_naked_variable] = STATE(18),
    [sym_string] = STATE(15),
    [sym_expression] = STATE(19),
    [sym_triple_quotes_naked_variable] = STATE(27),
    [sym_code_naked_variable] = STATE(27),
    [sym_nowiki_naked_variable] = STATE(27),
    [sym_escaped_naked_variable] = STATE(27),
    [sym_link] = STATE(27),
    [sym_literal] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(9),
    [sym_line_continuation] = ACTIONS(11),
    [sym_word] = ACTIONS(31),
    [anon_sym_DOLLAR] = ACTIONS(34),
    [sym_number] = ACTIONS(37),
    [aux_sym_string_token1] = ACTIONS(40),
    [aux_sym_string_token2] = ACTIONS(40),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(43),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(46),
    [anon_sym_LTnowiki_GT] = ACTIONS(49),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(52),
  },
  [STATE(3)] = {
    [sym_item] = STATE(29),
    [sym_comment] = STATE(3),
    [sym_naked_variable] = STATE(18),
    [sym_string] = STATE(15),
    [sym_expression] = STATE(19),
    [sym_triple_quotes_naked_variable] = STATE(27),
    [sym_code_naked_variable] = STATE(27),
    [sym_nowiki_naked_variable] = STATE(27),
    [sym_escaped_naked_variable] = STATE(27),
    [sym_link] = STATE(27),
    [sym_literal] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(9),
    [sym_line_continuation] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [anon_sym_DOLLAR] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [aux_sym_string_token1] = ACTIONS(19),
    [aux_sym_string_token2] = ACTIONS(19),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(21),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(23),
    [anon_sym_LTnowiki_GT] = ACTIONS(25),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      anon_sym_DOT,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    STATE(4), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_naked_variable_repeat1,
    STATE(7), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(59), 13,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [41] = 9,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(61), 1,
      anon_sym_DOT,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym_naked_variable_repeat1,
    STATE(5), 1,
      sym_comment,
    STATE(7), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(67), 13,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [82] = 8,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    STATE(6), 2,
      sym_comment,
      aux_sym_naked_variable_repeat1,
    STATE(7), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(71), 13,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [121] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_comment,
    ACTIONS(81), 15,
      sym_word,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [151] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_comment,
    ACTIONS(85), 15,
      sym_word,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [181] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_comment,
    ACTIONS(89), 15,
      sym_word,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [211] = 8,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    STATE(10), 2,
      sym_comment,
      aux_sym_naked_variable_repeat1,
    STATE(23), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(71), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [246] = 9,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      anon_sym_DOT,
    ACTIONS(99), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_naked_variable_repeat1,
    STATE(23), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(67), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [283] = 9,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      anon_sym_DOT,
    ACTIONS(99), 1,
      anon_sym_LBRACK,
    STATE(10), 1,
      aux_sym_naked_variable_repeat1,
    STATE(12), 1,
      sym_comment,
    STATE(23), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(59), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [320] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_comment,
    ACTIONS(103), 13,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [348] = 6,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(103), 11,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [378] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym_comment,
    ACTIONS(109), 13,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [406] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym_comment,
    ACTIONS(113), 13,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [434] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_comment,
    ACTIONS(117), 13,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [462] = 6,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      sym_comment,
    ACTIONS(117), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(122), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [492] = 7,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(129), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [524] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(131), 1,
      anon_sym_DOT,
    ACTIONS(134), 1,
      anon_sym_LBRACK,
    STATE(20), 2,
      sym_comment,
      aux_sym_naked_variable_repeat1,
    STATE(34), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(69), 8,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      anon_sym_LT_SLASHnowiki_GT,
  [555] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(137), 1,
      anon_sym_DOT,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    STATE(21), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_naked_variable_repeat1,
    STATE(34), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(65), 8,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      anon_sym_LT_SLASHnowiki_GT,
  [588] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(137), 1,
      anon_sym_DOT,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      aux_sym_naked_variable_repeat1,
    STATE(22), 1,
      sym_comment,
    STATE(34), 2,
      sym_dotProperty,
      sym_squareProperty,
    ACTIONS(57), 8,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      anon_sym_LT_SLASHnowiki_GT,
  [621] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_comment,
    ACTIONS(81), 11,
      sym_word,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [647] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym_comment,
    ACTIONS(85), 11,
      sym_word,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [673] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_comment,
    ACTIONS(89), 11,
      sym_word,
      anon_sym_DOLLAR,
      anon_sym_DOT,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [699] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym_comment,
    ACTIONS(143), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [723] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym_comment,
    ACTIONS(127), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [747] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_comment,
    ACTIONS(147), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [771] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      sym_comment,
    ACTIONS(151), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [795] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_comment,
    ACTIONS(155), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [819] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_comment,
    ACTIONS(159), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [843] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(32), 1,
      sym_comment,
    ACTIONS(83), 10,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      anon_sym_LT_SLASHnowiki_GT,
  [865] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      sym_comment,
    ACTIONS(163), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [889] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(34), 1,
      sym_comment,
    ACTIONS(79), 10,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      anon_sym_LT_SLASHnowiki_GT,
  [911] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    STATE(35), 1,
      sym_comment,
    ACTIONS(167), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [935] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(36), 1,
      sym_comment,
    ACTIONS(87), 10,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_RBRACE_RBRACE_RBRACE,
      anon_sym_LT_SLASHnowiki_GT,
  [957] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    STATE(37), 1,
      sym_comment,
    ACTIONS(171), 9,
      sym_word,
      anon_sym_DOLLAR,
      sym_number,
      aux_sym_string_token1,
      aux_sym_string_token2,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
      anon_sym_LBRACE_LBRACE_LBRACE,
      anon_sym_LTnowiki_GT,
      anon_sym_LBRACK_LBRACK,
  [981] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_DOLLAR,
    ACTIONS(175), 1,
      sym_number,
    STATE(38), 1,
      sym_comment,
    STATE(45), 1,
      sym_expression,
    STATE(50), 1,
      sym_string,
    ACTIONS(177), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(51), 2,
      sym_naked_variable,
      sym_literal,
  [1011] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(179), 1,
      anon_sym_DOLLAR,
    ACTIONS(181), 1,
      sym_number,
    STATE(13), 1,
      sym_expression,
    STATE(15), 1,
      sym_string,
    STATE(39), 1,
      sym_comment,
    ACTIONS(183), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(17), 2,
      sym_naked_variable,
      sym_literal,
  [1041] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_DOLLAR,
    ACTIONS(175), 1,
      sym_number,
    STATE(40), 1,
      sym_comment,
    STATE(50), 1,
      sym_string,
    STATE(53), 1,
      sym_expression,
    ACTIONS(177), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(51), 2,
      sym_naked_variable,
      sym_literal,
  [1071] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_DOLLAR,
    ACTIONS(175), 1,
      sym_number,
    STATE(41), 1,
      sym_comment,
    STATE(50), 1,
      sym_string,
    STATE(52), 1,
      sym_expression,
    ACTIONS(177), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(51), 2,
      sym_naked_variable,
      sym_literal,
  [1101] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(179), 1,
      anon_sym_DOLLAR,
    ACTIONS(181), 1,
      sym_number,
    STATE(14), 1,
      sym_expression,
    STATE(15), 1,
      sym_string,
    STATE(42), 1,
      sym_comment,
    ACTIONS(183), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(17), 2,
      sym_naked_variable,
      sym_literal,
  [1131] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_DOLLAR,
    ACTIONS(175), 1,
      sym_number,
    STATE(43), 1,
      sym_comment,
    STATE(50), 1,
      sym_string,
    STATE(54), 1,
      sym_expression,
    ACTIONS(177), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(51), 2,
      sym_naked_variable,
      sym_literal,
  [1161] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_DOLLAR,
    ACTIONS(175), 1,
      sym_number,
    STATE(44), 1,
      sym_comment,
    STATE(50), 1,
      sym_string,
    STATE(55), 1,
      sym_expression,
    ACTIONS(177), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(51), 2,
      sym_naked_variable,
      sym_literal,
  [1191] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(189), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1212] = 6,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(193), 1,
      anon_sym_DASH_DASH_GT,
    STATE(46), 1,
      sym_comment,
    STATE(47), 1,
      aux_sym_comment_repeat1,
    ACTIONS(191), 3,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [1233] = 5,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(198), 1,
      anon_sym_DASH_DASH_GT,
    STATE(47), 2,
      sym_comment,
      aux_sym_comment_repeat1,
    ACTIONS(195), 3,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [1252] = 6,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(200), 1,
      anon_sym_DASH_DASH_GT,
    STATE(46), 1,
      aux_sym_comment_repeat1,
    STATE(48), 1,
      sym_comment,
    ACTIONS(191), 3,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
  [1273] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(49), 1,
      sym_comment,
    ACTIONS(111), 5,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1290] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(50), 1,
      sym_comment,
    ACTIONS(107), 5,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1307] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(51), 1,
      sym_comment,
    ACTIONS(115), 5,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1324] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(52), 1,
      sym_comment,
    ACTIONS(101), 5,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1341] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    STATE(53), 1,
      sym_comment,
    ACTIONS(189), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(101), 3,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1360] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(202), 1,
      anon_sym_RBRACK,
    STATE(54), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(189), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1381] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
    STATE(55), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(189), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1402] = 4,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    STATE(56), 1,
      sym_comment,
    ACTIONS(206), 4,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
      anon_sym_DASH_DASH_GT,
  [1418] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(208), 1,
      anon_sym_PIPE,
    ACTIONS(210), 1,
      anon_sym_RBRACK_LBRACK,
    ACTIONS(212), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(57), 1,
      sym_comment,
  [1437] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(214), 1,
      anon_sym_DOLLAR,
    ACTIONS(216), 1,
      aux_sym_naked_variable_token1,
    STATE(30), 1,
      sym_naked_variable,
    STATE(58), 1,
      sym_comment,
  [1456] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(218), 1,
      anon_sym_RBRACK_LBRACK,
    ACTIONS(220), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(59), 1,
      sym_comment,
  [1472] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_DOLLAR,
    STATE(60), 1,
      sym_comment,
    STATE(70), 1,
      sym_naked_variable,
  [1488] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_DOLLAR,
    STATE(61), 1,
      sym_comment,
    STATE(71), 1,
      sym_naked_variable,
  [1504] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(173), 1,
      anon_sym_DOLLAR,
    STATE(62), 1,
      sym_comment,
    STATE(68), 1,
      sym_naked_variable,
  [1520] = 4,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(222), 1,
      sym_word_link,
    STATE(63), 1,
      sym_comment,
  [1533] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(224), 1,
      aux_sym_naked_variable_token1,
    STATE(64), 1,
      sym_comment,
  [1546] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(226), 1,
      aux_sym_naked_variable_token1,
    STATE(65), 1,
      sym_comment,
  [1559] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(220), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(66), 1,
      sym_comment,
  [1572] = 4,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(228), 1,
      sym_word_link,
    STATE(67), 1,
      sym_comment,
  [1585] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(230), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(68), 1,
      sym_comment,
  [1598] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(232), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(69), 1,
      sym_comment,
  [1611] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(234), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
    STATE(70), 1,
      sym_comment,
  [1624] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(236), 1,
      anon_sym_LT_SLASHnowiki_GT,
    STATE(71), 1,
      sym_comment,
  [1637] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      sym_comment,
  [1650] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(240), 1,
      aux_sym_naked_variable_token1,
    STATE(73), 1,
      sym_comment,
  [1663] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(242), 1,
      aux_sym_naked_variable_token1,
    STATE(74), 1,
      sym_comment,
  [1676] = 4,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(244), 1,
      sym_word_link,
    STATE(75), 1,
      sym_comment,
  [1689] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(216), 1,
      aux_sym_naked_variable_token1,
    STATE(76), 1,
      sym_comment,
  [1702] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(5), 1,
      sym_line_continuation,
    ACTIONS(246), 1,
      aux_sym_naked_variable_token1,
    STATE(77), 1,
      sym_comment,
  [1715] = 4,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      sym_line_continuation,
    ACTIONS(248), 1,
      sym_word_link,
    STATE(78), 1,
      sym_comment,
  [1728] = 1,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
  [1732] = 1,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 41,
  [SMALL_STATE(6)] = 82,
  [SMALL_STATE(7)] = 121,
  [SMALL_STATE(8)] = 151,
  [SMALL_STATE(9)] = 181,
  [SMALL_STATE(10)] = 211,
  [SMALL_STATE(11)] = 246,
  [SMALL_STATE(12)] = 283,
  [SMALL_STATE(13)] = 320,
  [SMALL_STATE(14)] = 348,
  [SMALL_STATE(15)] = 378,
  [SMALL_STATE(16)] = 406,
  [SMALL_STATE(17)] = 434,
  [SMALL_STATE(18)] = 462,
  [SMALL_STATE(19)] = 492,
  [SMALL_STATE(20)] = 524,
  [SMALL_STATE(21)] = 555,
  [SMALL_STATE(22)] = 588,
  [SMALL_STATE(23)] = 621,
  [SMALL_STATE(24)] = 647,
  [SMALL_STATE(25)] = 673,
  [SMALL_STATE(26)] = 699,
  [SMALL_STATE(27)] = 723,
  [SMALL_STATE(28)] = 747,
  [SMALL_STATE(29)] = 771,
  [SMALL_STATE(30)] = 795,
  [SMALL_STATE(31)] = 819,
  [SMALL_STATE(32)] = 843,
  [SMALL_STATE(33)] = 865,
  [SMALL_STATE(34)] = 889,
  [SMALL_STATE(35)] = 911,
  [SMALL_STATE(36)] = 935,
  [SMALL_STATE(37)] = 957,
  [SMALL_STATE(38)] = 981,
  [SMALL_STATE(39)] = 1011,
  [SMALL_STATE(40)] = 1041,
  [SMALL_STATE(41)] = 1071,
  [SMALL_STATE(42)] = 1101,
  [SMALL_STATE(43)] = 1131,
  [SMALL_STATE(44)] = 1161,
  [SMALL_STATE(45)] = 1191,
  [SMALL_STATE(46)] = 1212,
  [SMALL_STATE(47)] = 1233,
  [SMALL_STATE(48)] = 1252,
  [SMALL_STATE(49)] = 1273,
  [SMALL_STATE(50)] = 1290,
  [SMALL_STATE(51)] = 1307,
  [SMALL_STATE(52)] = 1324,
  [SMALL_STATE(53)] = 1341,
  [SMALL_STATE(54)] = 1360,
  [SMALL_STATE(55)] = 1381,
  [SMALL_STATE(56)] = 1402,
  [SMALL_STATE(57)] = 1418,
  [SMALL_STATE(58)] = 1437,
  [SMALL_STATE(59)] = 1456,
  [SMALL_STATE(60)] = 1472,
  [SMALL_STATE(61)] = 1488,
  [SMALL_STATE(62)] = 1504,
  [SMALL_STATE(63)] = 1520,
  [SMALL_STATE(64)] = 1533,
  [SMALL_STATE(65)] = 1546,
  [SMALL_STATE(66)] = 1559,
  [SMALL_STATE(67)] = 1572,
  [SMALL_STATE(68)] = 1585,
  [SMALL_STATE(69)] = 1598,
  [SMALL_STATE(70)] = 1611,
  [SMALL_STATE(71)] = 1624,
  [SMALL_STATE(72)] = 1637,
  [SMALL_STATE(73)] = 1650,
  [SMALL_STATE(74)] = 1663,
  [SMALL_STATE(75)] = 1676,
  [SMALL_STATE(76)] = 1689,
  [SMALL_STATE(77)] = 1702,
  [SMALL_STATE(78)] = 1715,
  [SMALL_STATE(79)] = 1728,
  [SMALL_STATE(80)] = 1732,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_naked_variable, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_naked_variable, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_naked_variable, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_naked_variable, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_naked_variable_repeat1, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotProperty, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotProperty, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_squareProperty, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_squareProperty, 3, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_item, 1, 0, 0), REDUCE(sym_expression, 1, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_item, 1, 0, 0), REDUCE(sym_expression, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_naked_variable_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 7, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 7, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_naked_variable, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_naked_variable, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nowiki_naked_variable, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nowiki_naked_variable, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triple_quotes_naked_variable, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_triple_quotes_naked_variable, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_naked_variable, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_naked_variable, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [238] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sugarcube(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sugarcube",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
